name: newsapi_jonathan
description: "A new Flutter project."

environment:
  sdk: ">=3.0.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  
    # Local database
  # UI & Animations
  google_fonts: ^6.0.0
  intl: ^0.19.0
  dio: ^5.4.0
  flutter_secure_storage: ^9.2.2
  flutter_map: ^8.2.2
  latlong2: ^0.9.0
  http: ^1.2.1
  shared_preferences: ^2.2.3
  url_launcher: ^6.2.6
  just_audio: ^0.9.36
  audio_session: ^0.1.15
  file_picker: ^8.0.0
  flutter_spinkit: ^5.2.0

dev_dependencies:
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  
flutter:
  uses-material-design: true
  assets:
    - assets/me.jpg
    - assets/default_cover.jpg
    - assets/Marin_Kitagawa.png